name: Setup Flutter Project

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      
    - name: Create Flutter Project
      run: flutter create --org com.example youtube_player_app .
      
    - name: Commit Project
      run: |
        git config user.email "github-actions@users.noreply.github.com"
        git config user.name "github-actions"
        git add .
        git commit -m "Create Flutter project" || exit 0
        git push
